discovery:
  image: sambamitra/discovery-server
  ports:
   - "8761:8761"
edge:
  image: sambamitra/edge-server
  ports:
   - "8761:8761"
  links:
   - discovery
   - apigw
   - book
apigw:
  image: sambamitra/api-gateway
  ports:
   - "8080:8080"
  links:
   - discovery
   - book
book:
  image: sambamitra/book
  ports:
   - "8081:8081"
  links:
   - discovery
