server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/employee