server:
  port: 8082
  ssl:
    key-store: classpath:server/employeeservice.jks
    key-store-password: s3cr3t
    key-password: s3cr3t
    trust-store: classpath:server/employeeservice.jks
    trust-store-password: s3cr3t
    client-auth: need
    protocol: TLSv1.2
  client:
    key-store: server/employeeservice.p12
    key-store-password: s3cr3t
    trust-store: server/employeeservice.jks
    trust-store-password: s3cr3t
    protocol: TLSv1.2
eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
  client:
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/employee