server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:server/registrationservice.p12
    key-store-password: s3cr3t
    key-password: s3cr3t
    client-auth: want
    protocol: TLSv1.2
eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
